
BOARD_TAG          = mega2560
ARDUINO_PORT       = /dev/cu.usb*
ARDUINO_DIR        = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR          =  ../arduino-mk
ARDUINO_LIBS       = MyEthernet MyEthernet/utility ICMPPing SPI Flash Sunrise DHT EEany Time Wire Wire/utility Messages DS1307RTC RTClib EEPROM twi
ARDUINO_SKETCHBOOK = ..

include ../arduino-mk/Arduino.mk